params:
  t:
    - 5000
  l:
    - 100
  m:
    - 5
  r:
    - 50
  'n':
    - 5
  v_m:
    - 0.005
  v_a:
    - 0
  v_m_e:
    - 0.01
  v_a_e:
    - 0.03
  a:
    - 0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 1
  e:
    - 0
    - 0.2
    - 0.4
    - 0.6
    - 0.8
    - 1
sensitivity_fixed_params:
  t:
    - 5000
  l:
    - 100
  m:
    - 5
  r:
    - 50
  'n':
    - 5
  v_m:
    - 0.005
  v_a:
    - 0
  v_m_e:
    - 0.01
  v_a_e:
    - 0.03
  a:
    - 0
    - 0.5
  e:
    - 0
    - 0.2
sensitivity_varying_params:
  t:
    - 4500
    - 5500
  l:
    - 90
    - 110
  m:
    - 4
    - 6
  r:
    - 45
    - 55
  'n':
    - 4
    - 6
  v_m:
    - 0.0045
    - 0.0055
  v_a:
    - 0.001
  v_m_e:
    - 0.009
    - 0.011
  v_a_e:
    - 0.027
    - 0.033
simulation_runs: 500
