params:
  t:
    - 5000
  l:
    - 100
  m:
    - 5
  r:
    - 50
  n:
    - 5
  v_m:
    - 0.005
  v_a:
    - 0
  v_m_e:
    - 0.01
  v_a_e:
    - 0.03
    - 0.1
    - 0.2
  a:
    - 0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 1.0
  e:
    - 0
    - 0.05
    - 0.1
    - 0.15
    - 0.2
    - 0.25
    - 0.3
simulation_runs: 90 # number of runs per parameter set

# test configuration
# params:
#   t:
#     - 5000
#   l:
#     - 100
#   m:
#     - 5
#   r:
#     - 50
#   n:
#     - 5
#   v_m:
#     - 0.005
#   v_a:
#     - 0
#   v_m_e:
#     - 0.01
#   v_a_e:
#     - 0.03
#   a:
#     - 0
#   e:
#     - 0
#     - 0.05
# simulation_runs: 100
